# Permalinks
permalink:           pretty

# Setup
title:               Даша Жданович
tagline:             Записки бесстрашного путешественника
url:                 http://blog.zhdanovich.eu
paginate:            10
baseurl:             ""
highlighter:         pygments

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Дарья Жданович
  url:               http://blog.zhdanovich.eu
  email:             darya_zhdanovich@outlook.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/dzhdanovich/dzhdanovich.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
